public class EmissionFactorWrapper {
    @AuraEnabled
    public List<Sobject> elecFctrList;
    @AuraEnabled
    public List<Sobject> othFctrList;
    @AuraEnabled
    public List<Sobject> airFctrList;
    @AuraEnabled
    public List<Sobject> grndFctrList;
    @AuraEnabled
    public List<Sobject> frgtFctrList;
    @AuraEnabled
    public List<Sobject> htlFctrList;
    @AuraEnabled
    public List<Sobject> refriFctrList;
    @AuraEnabled
    public List<Sobject> rntalFctrList;
}